bridge:
  email: my@email.com
  orport: 31001
  ptport: 31030
  nickname: UnNomDeRelai
  obfs4variables: 
    OBFS4_ENABLE_ADDITIONAL_VARIABLES: 1
    OBFS4V_AddressDisableIPv6: 1
    OBFS4V_RelayBandwidthRate: 100 Kbytes
    OBFS4V_RelayBandwidthBurst: 300 Kbytes
    OBFS4V_ExitPolicy: reject *:*

pvc:
  existingClaim: true
  storageClassName: longhorn
  name: obfs4-data-pvc

resources:
  limits:
    memory: 6Gi
  requests:
    memory: 1Gi

nodeSelector:
  kubernetes.io/hostname: mynodename

