apiVersion: apps/v1
kind: Deployment
metadata:
  name: obfs4-bridge
  labels:
    app: obfs4-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obfs4-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obfs4-bridge
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      securityContext:
        fsGroup: 2000
      containers:
        - env: 
            - name: EMAIL
              value: {{ .Values.bridge.email }}
            - name: NICKNAME
              value: {{ .Values.bridge.nickname }}
            - name: OR_PORT
              value: !!str {{ .Values.bridge.orport }}
            - name: PT_PORT
              value: !!str {{ .Values.bridge.ptport }}
            {{- $valuesMap := .Values.bridge.obfs4variables -}}
            {{- range $key, $value := $valuesMap }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          image: thetorproject/obfs4-bridge:latest
          name: obfs4-bridge
          ports:
            - containerPort: {{ .Values.bridge.orport }}
            - containerPort: {{ .Values.bridge.ptport }}
          volumeMounts:
            - mountPath: /var/lib/tor
              name: obfs4-bridge-data
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      restartPolicy: Always
      volumes:
        - name: obfs4-bridge-data
          persistentVolumeClaim:
            claimName: obfs4-data-pv-claim
