apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: obfs4-bridge
  labels:
    app: obfs4-bridge
spec:
  podSelector:
    matchLabels:
      app: obfs4-bridge 
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
    ports:
      - protocol: TCP
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
    ports:
      - protocol: TCP
        port: {{ .Values.bridge.orport }}
      - protocol: TCP
        port: {{ .Values.bridge.ptport }}
