{{- if not .Values.pvc.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: obfs4-bridge
  name: {{ .Values.pvc.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
{{- end }}
